# Generated by Django 4.2.20 on 2025-05-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='movie',
            field=models.ForeignKey(default='3d32f864-f172-4de2-b9d0-6819d3845210', on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
