# Generated by Django 4.2.20 on 2025-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_transaction_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='price',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket_status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Redeemed', 'Redeemed'), ('Expired', 'Expired')], default='VALID', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_method',
            field=models.CharField(choices=[('VISA', 'VISA'), ('Cash', 'Cash'), ('Gcash', 'Gcash')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
